/* Generated by Yosys 0.43 (git sha1 ead4718e5, g++ 14.1.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/build/yosys/src=/usr/src/debug/yosys -fPIC -Os) */

module sn74299(i_clock, i_s0, i_s1, i_g1, i_g2, i_clear, i_sl, i_sr, o_qA, o_qH, io_data);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire [7:0] _4_;
  wire _5_;
  reg [7:0] _6_;
  wire [7:0] _7_;
  wire [7:0] data;
  wire [1:0] func_sel;
  input i_clear;
  wire i_clear;
  input i_clock;
  wire i_clock;
  input i_g1;
  wire i_g1;
  input i_g2;
  wire i_g2;
  input i_s0;
  wire i_s0;
  input i_s1;
  wire i_s1;
  input i_sl;
  wire i_sl;
  input i_sr;
  wire i_sr;
  inout [7:0] io_data;
  wire [7:0] io_data;
  output o_qA;
  wire o_qA;
  output o_qH;
  wire o_qH;
  wire [1:0] out_en;
  assign _1_ = func_sel == 2'h3;
  assign _2_ = func_sel == 2'h1;
  assign _3_ = func_sel == 2'h2;
  function [7:0] \20 ;
    input [7:0] a;
    input [23:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \20  = b[7:0];
      3'b?1?:
        \20  = b[15:8];
      3'b1??:
        \20  = b[23:16];
      default:
        \20  = a;
    endcase
  endfunction
  assign _4_ = \20 (data, { data[6:0], i_sl, i_sr, data[7:1], io_data }, { _3_, _2_, _1_ });
  assign _5_ = out_en == 2'h0;
  always @(posedge i_clock, posedge _0_)
    if (_0_) _6_ <= 8'h00;
    else _6_ <= _4_;
  assign _7_ = _5_ ? data : 8'bz;
  assign _0_ = ~ i_clear;
  assign io_data = _7_;
  assign data = _6_;
  assign out_en = { i_g1, i_g2 };
  assign func_sel = { i_s1, i_s0 };
  assign o_qA = data[0];
  assign o_qH = data[7];
endmodule
