/* Generated by Yosys 0.43 (git sha1 ead4718e5, g++ 14.1.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/build/yosys/src=/usr/src/debug/yosys -fPIC -Os) */

module sn74163(i_clock, i_en, i_en_rco, i_clear, i_load, i_value, o_carry, o_value);
  wire _00_;
  wire _01_;
  wire _02_;
  reg [3:0] _03_;
  wire _04_;
  wire _05_;
  wire [3:0] _06_;
  wire [3:0] _07_;
  wire [3:0] _08_;
  wire [3:0] _09_;
  wire _10_;
  wire _11_;
  input i_clear;
  wire i_clear;
  input i_clock;
  wire i_clock;
  input i_en;
  wire i_en;
  input i_en_rco;
  wire i_en_rco;
  input i_load;
  wire i_load;
  input [3:0] i_value;
  wire [3:0] i_value;
  output o_carry;
  wire o_carry;
  output [3:0] o_value;
  wire [3:0] o_value;
  wire [3:0] r_value;
  assign _07_ = _05_ ? _06_ : r_value;
  assign _08_ = _04_ ? i_value : _07_;
  assign _09_ = _00_ ? 4'h0 : _08_;
  assign _10_ = i_en_rco & i_en;
  assign _11_ = r_value == 4'hf;
  assign _01_ = _11_ & _10_;
  assign _02_ = _01_ ? 1'h1 : 1'h0;
  always @(posedge i_clock)
    _03_ <= _09_;
  assign _00_ = ~ i_clear;
  assign _04_ = ~ i_load;
  assign _05_ = i_en_rco & i_en;
  assign _06_ = r_value + 4'h1;
  assign r_value = _03_;
  assign o_carry = _02_;
  assign o_value = r_value;
endmodule
